name: udlai_env
channels:
  - conda-forge
dependencies:
  # required
  - numpy
  - pandas
  # testing
  - pytest
  - black
  - flake8
  - isort
  - pytest-cov
  - pre-commit
  # documentation
  - sphinx
  - numpydoc
  - furo
